### ISSUE TITLE
democheckout

### ISSUE THREAD

**Issue by ThienTho123** [ThongNguyenDT/take-e-pay#1]
![Untitled](https://github.com/ThongNguyenDT/take-e-pay/assets/129725593/3728e7a8-dfa1-46c7-a0ce-975dfeb50387)

**Comment by ThienTho123** [comment]
![Uploading Screenshot 2023-12-14 231419.png…]()

**Comment by ThienTho123** [comment]
![Screenshot 2023-12-14 231419](https://github.com/ThongNguyenDT/take-e-pay/assets/129725593/44271701-43ea-492d-a04a-5ce6db108063)

**Comment by ThongNguyenDT** [comment]
fixed
